#encoding: utf-8
import os, sys

print("EJEMPLO DE FUNCION SPLIT QUE SIRVE PARA SEPARAR UN STRING")

 
print("EJEMPLO DE FUNCION SPLIT QUE SIRVE PARA SEPARAR UN STRING POR ESPACIO".split())

print("EJEMPLO,DE,FUNCION,SPLIT,QUE,SIRVE,PARA,SEPARAR,UN,STRING,POR,COMA".split(","))


