alfabeto="abcdefghijklmoprstuvwyz"
print(alfabeto)
alf_lista=list(alfabeto)
print(alf_lista)
print("ACCEDER A UN INDICE ")
print("A")
print(alf_lista.index("a"))
print("G")
print(alf_lista.index("g"))
print("W")
print(alf_lista.index("w"))
print("POSICION 10")
print(alf_lista[10])
print("POSICION -10 TAMBIEM SIRVE PARA LAS LISTAS")
print(alf_lista[-10])